package ru.rtds.pc.dto

data class DoorZoneProfileRequest(
    val name: String,
    val doorType: String = "CUSTOM",
    val lineYRatio: Float? = null,
    val lineAxRatio: Float? = null,
    val lineAyRatio: Float? = null,
    val lineBxRatio: Float? = null,
    val lineByRatio: Float? = null,
    val salonPolygon: List<LinePointDto> = emptyList(),
    val streetPolygon: List<LinePointDto> = emptyList(),
    val doorPolygon: List<LinePointDto> = emptyList(),
    val salonSpawnPolygon: List<LinePointDto> = emptyList(),
    val insideOnTop: Boolean? = null,
    val insideOnPositiveSide: Boolean? = null,
    val autoInitialOnboard: Boolean? = null,
    val initialOnboard: Int? = null,
)

data class DoorZoneProfileResponse(
    val id: String,
    val name: String,
    val doorType: String,
    val lineYRatio: Float?,
    val lineAxRatio: Float?,
    val lineAyRatio: Float?,
    val lineBxRatio: Float?,
    val lineByRatio: Float?,
    val salonPolygon: List<LinePointDto>,
    val streetPolygon: List<LinePointDto>,
    val doorPolygon: List<LinePointDto>,
    val salonSpawnPolygon: List<LinePointDto>,
    val insideOnTop: Boolean?,
    val insideOnPositiveSide: Boolean?,
    val autoInitialOnboard: Boolean?,
    val initialOnboard: Int?,
    val createdAtMs: Long,
    val updatedAtMs: Long,
)

data class CameraProfileBindingRequest(
    val recorderId: String,
    val cameraCode: String,
    val logicalDoor: String = "CUSTOM",
    val profileId: String?,
    val confirmedBy: String? = null,
    val previewSourcePath: String? = null,
    val previewFrameIndex: Int? = null,
)

data class CameraProfileBindingResponse(
    val id: String,
    val recorderId: String,
    val cameraCode: String,
    val logicalDoor: String,
    val profileId: String?,
    val profileName: String?,
    val active: Boolean,
    val confirmedBy: String?,
    val confirmedAtMs: Long?,
    val previewSourcePath: String?,
    val previewFrameIndex: Int?,
    val createdAtMs: Long,
    val updatedAtMs: Long,
)

data class ResolvedDoorConfigResponse(
    val recorderId: String?,
    val cameraCode: String?,
    val logicalDoor: String?,
    val ignored: Boolean,
    val classificationNeeded: Boolean,
    val profileId: String?,
    val profileName: String,
    val source: String,
    val lineYRatio: Float,
    val lineAxRatio: Float?,
    val lineAyRatio: Float?,
    val lineBxRatio: Float?,
    val lineByRatio: Float?,
    val salonPolygon: List<LinePointDto>,
    val streetPolygon: List<LinePointDto>,
    val doorPolygon: List<LinePointDto>,
    val salonSpawnPolygon: List<LinePointDto>,
    val insideOnTop: Boolean,
    val insideOnPositiveSide: Boolean?,
    val autoInitialOnboard: Boolean,
    val initialOnboard: Int,
)
