package ru.rtds.pc.dto

data class AnalysisResultResponse(
    val sessionId: String,
    val sourcePath: String,
    val originalRelativePath: String?,
    val videoName: String,
    val videoDeviceId: String?,
    val recordDate: String?,
    val channel: Int?,
    val cameraCode: String?,
    val eventCode: String?,
    val recordType: Int?,
    val clipStartedAtMs: Long?,
    val clipFinishedAtMs: Long?,
    val fileFlag: Int?,
    val fileUid: Long?,
    val sourceHash: String?,
    val source: String,
    val zoneProfileId: String?,
    val zoneProfileName: String?,
    val logicalDoor: String?,
    val status: String,
    val totalExited: Int,
    @Deprecated("Exit-only mode always reports zero boardings")
    val totalBoardings: Int,
    @Deprecated("Use totalExited")
    val totalAlightings: Int,
    val finalOnboard: Int,
    val initialOnboard: Int,
    val framesProcessed: Int,
    val durationMs: Long,
    val salonPolygon: List<LinePointDto>,
    val streetPolygon: List<LinePointDto>,
    val doorPolygon: List<LinePointDto>,
    val lineYRatio: Float,
    val insideOnTop: Boolean,
    val lineAxRatio: Float,
    val lineAyRatio: Float,
    val lineBxRatio: Float,
    val lineByRatio: Float,
    val insideOnPositiveSide: Boolean,
    val startedAtMs: Long,
    val finishedAtMs: Long,
    val errorMessage: String?,
)
